### PR TITLE
added some handling for data from different view types

### PR DESCRIPTION
**Pull request by tbenade**
a possible fix for 
https://github.com/ironSource/node-dynamodb-stream/issues/2

### CODE REVIEW

**Comment by kessler** [comment]
@tbenade bump :)

**Comment by tbenade** [comment]
sorry notifications werent reaching me will respond momentarily

**Comment by kessler** [comment]
@tbenade it is I who was sorry about the extra space to begin with, you were right to remove them... :)

**Comment by tbenade** [comment]
Been a while so a bit rusty. Looking as issue [#2](https://github.com/ironSource/node-dynamodb-stream/issues/2)
I think the problem was the module is essentially unusable if the 
StreamViewType is anything other than NEW_AND_OLD_IMAGES

[From documentation........](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDBStreams.html#describeStream-property)
Indicates the format of the records within this stream:

KEYS_ONLY - only the key attributes of items that were modified in the DynamoDB table.
NEW_IMAGE - entire item from the table, as it appeared after they were modified.
OLD_IMAGE - entire item from the table, as it appeared before they were modified.
NEW_AND_OLD_IMAGES - both the new and the old images of the items from the table.

**Pull request merged**
